#!/bin/bash


# script created by IamJony.

# My github https://github.com/IamJony



# Shadown Libraries url
anna='https://annas-archive.org/search?q='

# Directory
dir="$HOME/.bookScraping"

mkdir $dir/ 2>/dev/null &
rm $dir/.html_anna* 2>/dev/null &
 

# function scraping
scraping_full() {
	
	format_html=$(sed -n '/<div class="h-\[125\] js-scroll-hidden">/,/<div class="h-\[125\] ">/{//!p}' $dir/.html_anna > $dir/.html_anna_scraping_anna)
	title_book=$(sed -n 's/.*<h3 class="truncate text-xl font-bold">\([^<]*\)<\/h3>.*/\1/p' $dir/.html_anna_scraping_anna > $dir/.title_book_anna)
	book_autor=$(sed -n 's/^.*<div class="truncate italic">\([^<]*\)<\/div>.*$/\1/p' $dir/.html_anna_scraping_anna > $dir/.book_autor_anna)
	format_book=$(sed -n 's/^.*<div class="truncate text-xs text-gray-500">\([^<]*MB\).*$/\1/p' $dir/.html_anna_scraping_anna > $dir/.format_book_anna)
	link_page=$(sed -n 's/^.*<a[^>]*href="\([^"]*\)".*$/\1/p' $dir/.html_anna_scraping_anna | sed -n '/md5/p' > $dir/.link_page_anna)
	md5=$(cat $dir/.link_page_anna)

	file1="$dir/.title_book_anna"
	file2="$dir/.book_autor_anna"
	file3="$dir/.format_book_anna"
	file4="$dir/.link_page_anna"
	file5="$dir/.donwload_link"
	
#Contador
line_num=1
	
while true; do

    # Imprimir la primera linea de los archivos
    echo "Title: $(sed -n "${line_num}p" "${file1}")"
    echo "Author: $(sed -n "${line_num}p" "${file2}")"
    echo "Format: $(sed -n "${line_num}p" "${file3}")"
	echo "Link_page: https://annas-archive.org$(sed -n "${line_num}p" "${file4}")"
	donwload_link=$(curl https://annas-archive.org$(sed -n "${line_num}p" "${file4}") | grep -oP '<li>.*?\K(?<=href=")[^"]*(?=")' > $dir/.donwload_link)
	echo "Download: $(cat ${file5})"
	echo -e ''
    echo -e '============================'
	echo -e ''
    # Incrementar el número de línea
    line_num=$((line_num+1))
    
    # Verificar si se llegó al final del archivo 1
    if [[ $(sed -n "$=" "${file1}") -lt $line_num ]]; then
        break
    fi
done
	
}

scraping_fast() {
	
	format_html=$(sed -n '/<div class="h-\[125\] js-scroll-hidden">/,/<div class="h-\[125\] ">/{//!p}' $dir/.html_anna > $dir/.html_anna_scraping_anna)
	title_book=$(sed -n 's/.*<h3 class="truncate text-xl font-bold">\([^<]*\)<\/h3>.*/\1/p' $dir/.html_anna_scraping_anna > $dir/.title_book_anna)
	book_autor=$(sed -n 's/^.*<div class="truncate italic">\([^<]*\)<\/div>.*$/\1/p' $dir/.html_anna_scraping_anna > $dir/.book_autor_anna)
	format_book=$(sed -n 's/^.*<div class="truncate text-xs text-gray-500">\([^<]*MB\).*$/\1/p' $dir/.html_anna_scraping_anna > $dir/.format_book_anna)
	link_page=$(sed -n 's/^.*<a[^>]*href="\([^"]*\)".*$/\1/p' $dir/.html_anna_scraping_anna | sed -n '/md5/p' > $dir/.link_page_anna)
	md5=$(cat $dir/.link_page_anna)

	file1="$dir/.title_book_anna"
	file2="$dir/.book_autor_anna"
	file3="$dir/.format_book_anna"
	file4="$dir/.link_page_anna"

# contador
line_num=1

	
while true; do

    # Imprimir la primera linea de los archivos
    echo "Title: $(sed -n "${line_num}p" "${file1}")"
    echo "Author: $(sed -n "${line_num}p" "${file2}")"
    echo "Format: $(sed -n "${line_num}p" "${file3}")"
	echo "Link_page: https://annas-archive.org$(sed -n "${line_num}p" "${file4}")"
	echo -e ''
    echo -e '============================'
	echo -e ''
    # Incrementar el número de línea
    line_num=$((line_num+1))
    
    # Verificar si se llegó al final del archivo 1
    if [[ $(sed -n "$=" "${file1}") -lt $line_num ]]; then
        break
    fi
done
	
}


if  [[ $1 = "--fast" ]]; then
	read -p "Ingresa un valor: " input &&
	input=${input// /+}
	curl "$anna""$input" >> $dir/.html_anna
	scraping_fast > $HOME/result
elif  [[ $1 = "--full" ]]; then
	read -p "Ingresa un valor: " input &&
	input=${input// /+}
	curl "$anna""$input" >> $dir/.html_anna
	scraping_full > $HOME/result
else
	
	cat <<- _EOF_
	No option specified, Available options:
	  --fast	--full 
	
	_EOF_
fi





exit 0 



