#!/bin/bash

# Created by IamJony
# My github: https://github.com/IamJony
# DESCRIPTION: a bash script for book scraping
# Version: 1.0-1

# Shadown Libraries url

anna='https://annas-archive.org/search?q='
pdfdrive='https://es.pdfdrive.com/search?q='

# Directory
dir="$HOME/.bookScraping"

mkdir $dir/ 2>/dev/null &
rm $dir/.html_anna* 2>/dev/null &
 

scraping_fast() {
	
#	format_html=$(sed -n '/<div class="h-\[125\] js-scroll-hidden">/,/<div class="h-\[125\] ">/{//!p}' $dir/.html_anna > $dir/.html_anna_scraping_anna)
	title_book=$(sed -n 's/.*<h3 class="truncate text-xl font-bold">\([^<]*\)<\/h3>.*/\1/p' $dir/.html_anna > $dir/.title_book_anna)
	book_autor=$(sed -n 's/^.*<div class="truncate italic">\([^<]*\)<\/div>.*$/\1/p' $dir/.html_anna > $dir/.book_autor_anna)
	format_book=$(sed -n 's/^.*<div class="truncate text-xs text-gray-500">\([^<]*MB\).*$/\1/p' $dir/.html_anna > $dir/.format_book_anna)
	link_page=$(sed -n 's/^.*<a[^>]*href="\([^"]*\)".*$/\1/p' $dir/.html_anna | sed -n '/md5/p' > $dir/.link_page_anna)
	md5=$(cat $dir/.link_page_anna)

	file1="$dir/.title_book_anna"
	file2="$dir/.book_autor_anna"
	file3="$dir/.format_book_anna"
	file4="$dir/.link_page_anna"

# contador
line_num=1

	
while true; do

    # Imprimir la primera linea de los archivos
    echo "$(sed -n "${line_num}p" "${file1}") | $(sed -n "${line_num}p" "${file2}") | $(sed -n "${line_num}p" "${file3}")"
	#~ echo "Link_page: https://annas-archive.org$(sed -n "${line_num}p" "${file4}")"
    # Incrementar el número de líne
    
    line_num=$((line_num+1))
    
    # Verificar si se llegó al final del archivo 1
    if [[ $(sed -n "$=" "${file1}") -lt $line_num ]]; then
        break
    fi
done
	
}



	read -p "Ingresa un valor: " input &&
	input=${input// /+}
	curl "$anna""$input" >> $dir/.html_anna
	scraping_fast > $dir/result
	
	
# FZF
export FZF_DEFAULT_OPTS="--bind='ctrl-x:execute(exit 0)+abort'"
	
# Leer el archivo y guardar cada línea en un array
if [ ! -s $dir/.title_book_anna ]; then
  echo -e $BRed'no se encontraron resultados'
  sleep 2
  clear
  exit 1
fi

readarray -t LINES < $dir/result

if [ ${#LINES[@]} -eq 0 ]; then
  echo "No se encontraron resultados."
  exit 1
fi

OPTIONS=()
for i in "${!LINES[@]}"; do
  OPTIONS+=("$i ${LINES[$i]}")
done

# Ejecutar FZF y obtener la selección del usuario
OPTION=$(printf '%s\n' "${OPTIONS[@]}" | fzf | awk '{print $1}')

# Validar la selección del usuario
if [[ "$OPTION" =~ ^[0-9]+$ && "$OPTION" -ge 0 && "$OPTION" -lt "${#LINES[@]}" ]]; then
  echo "==========="
  echo "Ha seleccionado la opción $OPTION: ${LINES[$OPTION]}"
  ANOTHER_FILE_LINE=$(sed -n "$((OPTION+1))p" $dir/.link_page_anna)
  curl https://annas-archive.org$ANOTHER_FILE_LINE | grep -oP '<li>.*?\K(?<=href=")[^"]*(?=")' > $dir/.donwload_link 

  

readarray -t urls < $dir/.donwload_link

for url in "${urls[@]}"
do
    filename=$(basename "$url")
    if [[ $filename =~ \.(pdf|epub|txt|zip|rar)$ ]]; then
        wget -nc -P "$dir/" "$url"
        if [ $? -eq 0 ]; then
            echo "Descarga exitosa: $filename"
            break
        fi
    fi
done
else
  echo "No se seleccionó ninguna opción."
  exit 1

fi
